<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="63.700" timestamp="2020-03-25T18:12:48.386740"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="common/save_fail_picture.py" line="9" name="test_temp_equal" time="49.972"><failure message="assert False">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109ab3710&gt;
args = (), kwargs = {}

    def inner(self, *args, **kwargs):
&gt;       result = function(self, *args, **kwargs)

common/save_fail_picture.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109ab3710&gt;

    @get_screen_shot
    def test_temp_equal(self):
        self.weather_condition_business = WeatherCompareBusiness(self.driver)
        result = self.weather_condition_business.compare_temp()
        print(&quot;result&quot;, result)
&gt;       assert result
E       assert False

test_case/test_weather_condition.py:24: AssertionError</failure></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="14" name="test_weather_desc_equal" time="12.879"></testcase></testsuite></testsuites>