<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="2" failures="0" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="27.766" timestamp="2020-03-25T21:27:12.262534"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="24" name="test_weather_desc_equal" time="20.522"><error message="test setup failure">cls = &lt;class &apos;_pytest.runner.CallInfo&apos;&gt;
func = &lt;function call_runtest_hook.&lt;locals&gt;.&lt;lambda&gt; at 0x109de5b70&gt;
when = &apos;setup&apos;
reraise = (&lt;class &apos;_pytest.outcomes.Exit&apos;&gt;, &lt;class &apos;KeyboardInterrupt&apos;&gt;)

    @classmethod
    def from_call(cls, func, when, reraise=None):
        #: context of invocation: one of &quot;setup&quot;, &quot;call&quot;,
        #: &quot;teardown&quot;, &quot;memocollect&quot;
        start = time()
        excinfo = None
        try:
&gt;           result = func()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/runner.py:229: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/runner.py:201: in &lt;lambda&gt;
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py:92: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py:86: in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/nose.py:12: in pytest_runtest_setup
    call_optional(item.parent.obj, &quot;setup&quot;)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109ea4518&gt;
name = &apos;setup&apos;

    def call_optional(obj, name):
        method = getattr(obj, name, None)
        isfixture = hasattr(method, &quot;_pytestfixturefunction&quot;)
        if method is not None and not isfixture and callable(method):
            # If there&apos;s any problems allow the exception to raise rather than
            # silently ignoring them
&gt;           method()
E           TypeError: setup() missing 1 required positional argument: &apos;browser&apos;

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/nose.py:37: TypeError</error></testcase><testcase time="0.001"></testcase><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/main.py&quot;, line 193, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/main.py&quot;, line 237, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py&quot;, line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py&quot;, line 86, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/main.py&quot;, line 258, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py&quot;, line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py&quot;, line 86, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pytest_rerunfailures.py&quot;, line 200, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/runner.py&quot;, line 89, in runtestprotocol
    rep = call_and_report(item, &quot;setup&quot;, log)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/runner.py&quot;, line 178, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py&quot;, line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/manager.py&quot;, line 86, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py&quot;, line 203, in _multicall
    gen.send(outcome)
  File &quot;/Users/qing.li/PycharmProjects/moji_ui_app/conftest.py&quot;, line 30, in pytest_runtest_makereport
    screen_img = _capture_screenshot()
  File &quot;/Users/qing.li/PycharmProjects/moji_ui_app/conftest.py&quot;, line 45, in _capture_screenshot
    return driver.get_screenshot_as_base64()
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py&quot;, line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)[&apos;value&apos;]
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py&quot;, line 321, in execute
    self.error_handler.check_response(response)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appium/webdriver/errorhandler.py&quot;, line 29, in check_response
    raise wde
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appium/webdriver/errorhandler.py&quot;, line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File &quot;/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py&quot;, line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started</error></testcase></testsuite></testsuites>