<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="2" hostname="liqingMacBook-Pro.local" name="pytest" skipped="0" tests="2" time="0.353" timestamp="2020-03-24T23:23:00.724571"><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="common/save_fail_picture.py" line="9" name="test_temp_equal" time="0.002"><failure message="AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109a03048&gt;
args = (), kwargs = {}

    def inner(self, *args, **kwargs):
        print(&quot;heello&quot;)
        try:
&gt;           function(self, *args, **kwargs)

common/save_fail_picture.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109a03048&gt;

    @get_screen_shot
    def test_temp_equal(self):
&gt;       self.weather_condition_business = WeatherCompareBusiness(self.driver)
E       AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;

test_case/test_weather_condition.py:21: AttributeError</failure></testcase><testcase classname="test_case.test_weather_condition.TestWeatherCondition" file="test_case/test_weather_condition.py" line="14" name="test_weather_desc_equal" time="0.001"><failure message="AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;">self = &lt;test_case.test_weather_condition.TestWeatherCondition object at 0x109a21eb8&gt;

    def test_weather_desc_equal(self):
&gt;       self.weather_condition_business = WeatherCompareBusiness(self.driver)
E       AttributeError: &apos;TestWeatherCondition&apos; object has no attribute &apos;driver&apos;

test_case/test_weather_condition.py:16: AttributeError</failure></testcase></testsuite></testsuites>